### ISSUE TITLE
SERIAL versus Serial

### ISSUE THREAD

**Issue by raster** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#12]
In the example sketch DHTtester.ino the lines that use serial commands are all uppercase (SERIAL) when the should be first letter uppercase only (Serial) to work. Example; Serial.begin, Serial.print, etc... (Not SERIAL.begin, SERIAL.print, etc.) With the syntax error the sketch will not compile.

**Comment by Pillar1989** [comment]
This must be a copy and paste error. Thanks,
