### ISSUE TITLE
Only zero returned with the test project

### ISSUE THREAD

**Issue by PetitEtCroustillant** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#14]
Hello, i'm trying to use the test project to read temp and humidity but it's just returning 0.

I'm using a MRKfox 1200 board and the grovePiboard with a DHT11 sensor.

Someone have a possible fix ?

**Comment by RoSchmi** [comment]
I had a similar problem with the DHT22 sensor on the Wio Terminal. I finally solved the issue by changing the Count value in the constructor of the DHT class from 25 (default value) to 20 (I am still testing what the best value is).
DHT dht(DHTPIN, DHTTYPE, 20);

**Comment by Pillar1989** [comment]
@IsQianGe

**Comment by tyihuang** [comment]
Hello, the default sample code uses the sensor DHT20 If you use DHT11 then you should delete the "//" in line 7 and comment out the 8 line
![image](https://user-images.githubusercontent.com/56999025/124226105-2083e400-db3b-11eb-9b5f-dd152efe3634.png)
