### ISSUE TITLE
Counter cnt in line 54 should be initialized

### ISSUE THREAD

**Issue by pmossel** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#16]
Since the v1.2 DHT sensor is part of the hardware for the 2021 course "IoT for Beginners (SKU E21000021)", this is still a relevant fix.

Counter cnt in line 54 should be initialized to zero to avoid compiler/linter issues.:

 uint32_t cnt = 0;

Furthermore, in line 322, variable ret is declared but never used. It should be removed.
int ret = 0 

Finally, the VSCODE C++ compiler flags line 322: suggests parentheses around comparison in operand of '&'
while (statu & 0x80 == 0x80) {

should read

while ((statu & 0x80) == 0x80) {

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor/pull/17/commits/e22ddd6a8239d812ce049f3497f13c2be1be1294 @pmossel  any idea ?

**Comment by zzff-sys** [comment]
Thank you very much for your suggestion. I have checked the code according to your suggestion and modified the code of V1.2 DHT sensor. @pmossel
