### ISSUE TITLE
"'Wire' was not declared in this scope"

### ISSUE THREAD

**Issue by efeefe** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#18]
When I try to run the example, I get the following error:

'Wire' was not declared in this scope

**Comment by TheCre8r** [comment]
Add the following code to the top under `#include "DHT.h"`
```c
#include <Wire.h> 
```

**Comment by Pillar1989** [comment]
@efeefe @TheCre8r Actually, We have the code, https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor/blob/master/DHT.h#L8 
Remember, this software needs use in the Arduino environment.
