### ISSUE TITLE
Why do not define the NAN as sqrt(-1)

### ISSUE THREAD

**Issue by francescofiorenza** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#6]
I decided to set #define NAN as sqrt(-1) instead of #define NAN 0 because a read of the temperature equal to zero is indistinguishable from a fail. It is possible to change also the library?

**Comment by KillingJacky** [comment]
Hi @francescofiorenza 
Fix. Used the NAN defination in C99 standard, which can be tested with `isnan(x)` function.
