### ISSUE TITLE
Error Compiling ESP32 - DHT in Arduino IDE

### ISSUE THREAD

**Issue by skrishna-07** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#7]
I just started learning ESP32, Here I'm received the first set of problem. Help me out to solve the issue. Followed the instruction from
https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md
and tried some examples and it works fine. I decided to take it to next level.
I tried to read the Temperature and Humidity using DHT11 grove sensor. I installed the DHT library from
https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor
While compiling I encounted the following error
"  Arduino: 1.8.6 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default, QIO, 80MHz, 4MB (32Mb), 115200, None"

Multiple libraries were found for "DHT.h"
In file included from C:\Users\*****\Documents\Arduino\libraries\DHT-sensor-library-master\DHT_U.cpp:22:0:

 Used: C:\Users\*****\Documents\Arduino\libraries\DHT-sensor-library-master
C:\Users\*****\Documents\Arduino\libraries\DHT-sensor-library-master\DHT_U.h:25:29: fatal error: Adafruit_Sensor.h: No such file or directory

 Not used: C:\Users\*****\Documents\Arduino\libraries\Grove_Temperature_And_Humidity_Sensor-master
compilation terminated.

exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences."

**Comment by KillingJacky** [comment]
The error says that you've installed more than one libraries that contains the `DHT.h` file, and the IDE picked the library not for Seeed Grove.
